//=========================================================================
//
//  Part of units package -- a Java version of GNU Units program.
//
//  Units is a program for unit conversion originally written in C
//  by Adrian Mariano (adrian@cam.cornell.edu.).
//  Copyright (C) 1996, 1997, 1999, 2000, 2001, 2002, 2003, 2004,
//  2005, 2006, 2007, 2009, 2011 by Free Software Foundation, Inc.
//
//  Java version Copyright (C) 2003, 2004, 2005, 2006, 2007, 2008,
//  2009, 2011, 2012 by Roman R Redziejowski (www.romanredz.se).
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program. If not, see <http://www.gnu.org/licenses/>.
//
//-------------------------------------------------------------------------
//
//  Change log
//
//  Version 1.89.J01.
//   120201 Created for this version.
//
//=========================================================================


line       = "!" command
           / space definition ;

command    = "locale " argument EOL {locale}
           / "locale" EOL {badloc}
           / "endlocale" EOL {endlocale}
           / "include " argument EOL {include}
           / "include" EOL {badincl}
           / "unitlist " space name space argument EOL {unitlist}
           / "unitlist" space EOL {badlist}
           / "utf8" EOL
           / "endutf8" EOL
           / skip EOL {badcomm}
           ;

           // The last alternative above ensures that 'command'
           // never fails, so 'line' will never backtrack
           // to process the line starting with '!' as a definition.
           // (A 'name' is allowed to start with '!'.)


definition = name [ \t] def EOL {unitdef}
           / name "(" param ")" space "[" dim ";" dim "]" def (";" def)? EOL {funcdef1}
           / name "(" param ")" space "[" skip EOL {baddim}
           / name "(" param ")" def (";" def)? EOL {funcdef2}
           / name "(" skip EOL {badfunc}
           / name "[" tabunit "]" space pair+ EOL {tabdef}
           / name "[" skip EOL {badtab}
           / name EOL {badunit}
           / EOL
           ;

           // Note that 'name' can be any string up to a blank,
           // '(', '[', or end of line; all these alternatives
           // are exhausted above.
           // The alternatives with actions 'baddim', 'badfunc',
           // and 'badtab' prevent backtracking after the recognized
           // portion excludes further success.
           // To avoid rescanning of the initial postion, we use
           // memoizing version of the parser that caches one result.


argument = _* ;

def      = ^[;]* ;

name     = ^[[( \t]+ ;

param    = ^[)]+ ;

tabunit  = ^[\]]+ ;

dim      = ^[\];]* ;

pair     = number number ("," space)? {pair};

number   = sign? mantissa exponent? space {number} ;

mantissa = "." digits / digits ("." digits?)? ;

exponent = [Ee] sign? digits ;

sign     = [+-] <sign> ;

digits   = [0-9]+ ;

space    = [ \t]* ;

skip     = _* ;

EOL      = !_ ;
